name: jaanerikarnia
favicon: null
layout_spectrum: 0.5747881454881281
typography_spectrum: 0.5061211048159748
title: JAAN-ERIK ARNIA
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#00264d'
    - '#973900'
    - '#fe8800'
    - '#ffe682'
  brandStrength: 0.9375
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
